const prisma = require("../prisma");
const dbLosAngeles = [
  {
    time: new Date(Date.parse(new Date()) + 1 * 1000 * 60 * 60 * 24).toJSON(),
    title: "Hayato",
    category: "reservation",
    description: "Los Angeles restautant",
    price: 10,
    quantity: 1,
    upload: "1700626869150.png",
    address1: "1320 E 7th st #126",
    address2: " ",
    city: "Los Angeles",
    zip: "90021",
    state: "CA",
    country: "US",
  },
  {
    time: new Date(Date.parse(new Date()) + 2 * 1000 * 60 * 60 * 24).toJSON(),
    title: "Orsa and Winsion",
    category: "reservation",
    description: "Los Angeles restautant",
    price: 10,
    quantity: 1,
    upload: "1700626869150.png",
    address1: "Farmers and merchants Bank Buliding, 122 4th St",
    address2: " ",
    city: "Los Angeles",
    zip: "90013",
    state: "CA",
    country: "US",
  },
  {
    time: new Date(Date.parse(new Date()) + 3 * 1000 * 60 * 60 * 24).toJSON(),
    title: "Bestia",
    category: "reservation",
    description: "Los Angeles restautant",
    price: 10,
    quantity: 1,
    upload: "1700626869150.png",
    address1: "2121 E 7th Pl",
    address2: " ",
    city: "Los Angeles",
    zip: "90021",
    state: "CA",
    country: "US",
  },
  {
    time: new Date(Date.parse(new Date()) + 4 * 1000 * 60 * 60 * 24).toJSON(),
    title: "Republique",
    category: "reservation",
    description: "Los Angeles restautant",
    price: 10,
    quantity: 1,
    upload: "1700626869150.png",
    address1: "624 S La Brea Ave",
    address2: " ",
    city: "Los Angeles",
    zip: "90036",
    state: "CA",
    country: "US",
  },
  {
    time: new Date(Date.parse(new Date()) + 5 * 1000 * 60 * 60 * 24).toJSON(),
    title: "Jitlada",
    category: "reservation",
    description: "Los Angeles restautant",
    price: 10,
    quantity: 1,
    upload: "1700626869150.png",
    address1: "5233 Sunset Blvd",
    address2: " ",
    city: "Los Angeles",
    zip: "90027",
    state: "CA",
    country: "US",
  },
];
const dbChicagoBoston = [
  {
    time: new Date(Date.parse(new Date()) + 1 * 1000 * 60 * 60 * 24).toJSON(),
    title: "Monteverde Restaurant & Pastificio",
    category: "reservation",
    description: "Chicago restautant",
    price: 10,
    quantity: 1,
    upload: "1700626869150.png",
    address1: "1020 W Madison St",
    address2: " ",
    city: "Chicago",
    zip: "60607",
    state: "IL",
    country: "US",
  },
  {
    time: new Date(Date.parse(new Date()) + 2 * 1000 * 60 * 60 * 24).toJSON(),
    title: "Au Cheval",
    category: "reservation",
    description: "Chicago restautant",
    price: 10,
    quantity: 1,
    upload: "1700626869150.png",
    address1: "800 W Randolph st",
    address2: " ",
    city: "Chicago",
    zip: "60607",
    state: "IL",
    country: "US",
  },
  {
    time: new Date(Date.parse(new Date()) + 3 * 1000 * 60 * 60 * 24).toJSON(),
    title: "The Gage",
    category: "reservation",
    description: "Chicago restautant",
    price: 10,
    quantity: 1,
    upload: "1700626869150.png",
    address1: "24 S Michigan Ave",
    address2: " ",
    city: "Chicago",
    zip: "60603",
    state: "IL",
    country: "US",
  },
  {
    time: new Date(Date.parse(new Date()) + 4 * 1000 * 60 * 60 * 24).toJSON(),
    title: "Catch 35",
    category: "reservation",
    description: "Chicago restautant",
    price: 10,
    quantity: 1,
    upload: "1700626869150.png",
    address1: "35 W Wacker Dr",
    address2: " ",
    city: "Chicago",
    zip: "60601",
    state: "IL",
    country: "US",
  },
  {
    time: new Date(Date.parse(new Date()) + 5 * 1000 * 60 * 60 * 24).toJSON(),
    title: "Acanto",
    category: "reservation",
    description: "Chicago restautant",
    price: 10,
    quantity: 1,
    upload: "1700626869150.png",
    address1: "18 S Michigan Ave",
    address2: " ",
    city: "Chicago",
    zip: "60603",
    state: "IL",
    country: "US",
  },
  {
    time: new Date(Date.parse(new Date()) + 1 * 1000 * 60 * 60 * 24).toJSON(),
    title: "Acanto",
    category: "reservation",
    description: "Boston restautant",
    price: 10,
    quantity: 1,
    upload: "1700626869150.png",
    address1: "279 Dartmouth St",
    address2: " ",
    city: "Boston",
    zip: "02116",
    state: "MA",
    country: "US",
  },
  {
    time: new Date(Date.parse(new Date()) + 2 * 1000 * 60 * 60 * 24).toJSON(),
    title: "Summer Shack",
    category: "reservation",
    description: "Boston restautant",
    price: 10,
    quantity: 1,
    upload: "1700626869150.png",
    address1: "50 Dalton St",
    address2: " ",
    city: "Boston",
    zip: "02115",
    state: "MA",
    country: "US",
  },
  {
    time: new Date(Date.parse(new Date()) + 3 * 1000 * 60 * 60 * 24).toJSON(),
    title: "Trade",
    category: "reservation",
    description: "Boston restautant",
    price: 10,
    quantity: 1,
    upload: "1700626869150.png",
    address1: "540 Atlantic Ave",
    address2: " ",
    city: "Boston",
    zip: "02110",
    state: "MA",
    country: "US",
  },
  {
    time: new Date(Date.parse(new Date()) + 4 * 1000 * 60 * 60 * 24).toJSON(),
    title: "Myers+Chang",
    category: "reservation",
    description: "Boston restautant",
    price: 10,
    quantity: 1,
    upload: "1700626869150.png",
    address1: "1145 Washington St",
    address2: " ",
    city: "Boston",
    zip: "02118",
    state: "MA",
    country: "US",
  },
  {
    time: new Date(Date.parse(new Date()) + 5 * 1000 * 60 * 60 * 24).toJSON(),
    title: "The Q",
    category: "reservation",
    description: "Boston restautant",
    price: 10,
    quantity: 1,
    upload: "1700626869150.png",
    address1: "660 Washington St",
    address2: " ",
    city: "Boston",
    zip: "02111",
    state: "MA",
    country: "US",
  },
];
const dbNewYork = [
  {
    time: new Date(Date.parse(new Date()) + 1 * 1000 * 60 * 60 * 24).toJSON(),
    title: "Carbone",
    category: "reservation",
    description: "New York restaurant",
    price: 10,
    quantity: 1,
    upload: "1700626869150.png",
    address1: "181 Thompson street",
    address2: " ",
    city: "New York",
    zip: "10012",
    state: "NY",
    country: "US",
  },
  {
    time: new Date(Date.parse(new Date()) + 4 * 1000 * 60 * 60 * 24).toJSON(),
    title: "COTE",
    category: "reservation",
    description: "New York restaurant",
    price: 10,
    quantity: 1,
    upload: "1700626869150.png",
    address1: "16 W22 Street",
    address2: " ",
    city: "New York",
    zip: "10012",
    state: "NY",
    country: "US",
  },
  {
    time: new Date(Date.parse(new Date()) + 6 * 1000 * 60 * 60 * 24).toJSON(),
    title: "Cafe Mogador",
    category: "reservation",
    description: "New York restaurant",
    price: 10,
    quantity: 1,
    upload: "1700626869150.png",
    address1: "133 Wythe Ave",
    address2: " ",
    city: "Brooklyn",
    zip: "11249",
    state: "NY",
    country: "US",
  },
  {
    time: new Date(Date.parse(new Date()) + 4 * 1000 * 60 * 60 * 24).toJSON(),
    title: "Cocoron",
    category: "reservation",
    description: "New York restaurant",
    price: 10,
    quantity: 1,
    upload: "1700626869150.png",
    address1: "16 Delancey St",
    address2: " ",
    city: "New York",
    zip: "10002",
    state: "NY",
    country: "US",
  },
  {
    time: new Date(Date.parse(new Date()) + 4 * 1000 * 60 * 60 * 24).toJSON(),
    title: "Bacaro",
    category: "reservation",
    description: "New York restaurant",
    price: 10,
    quantity: 1,
    upload: "1700626869150.png",
    address1: "136 Division Street",
    address2: " ",
    city: "New York",
    zip: "10002",
    state: "NY",
    country: "US",
  },
  {
    time: new Date(Date.parse(new Date()) + 4 * 1000 * 60 * 60 * 24).toJSON(),
    title: "AMC Empire",
    category: "movies",
    description: "New York movies",
    price: 10,
    quantity: 1,
    upload: "1700626869150.png",
    address1: "25 - 234 W42 st",
    address2: " ",
    city: "New York",
    zip: "10036",
    state: "NY",
    country: "US",
  },
  {
    time: new Date(Date.parse(new Date()) + 9 * 1000 * 60 * 60 * 24).toJSON(),
    title: "IPIC Theater",
    category: "movies",
    description: "New York movies",
    price: 10,
    quantity: 1,
    upload: "1700626869150.png",
    address1: "11 Fullton St",
    address2: " ",
    city: "New York",
    zip: "10038",
    state: "NY",
    country: "US",
  },
  {
    time: new Date(Date.parse(new Date()) + 3 * 1000 * 60 * 60 * 24).toJSON(),
    title: "BAM strong",
    category: "concert",
    description: "New York concert",
    price: 10,
    quantity: 1,
    upload: "1700626869150.png",
    address1: "651 Fulton",
    address2: " ",
    city: "New York",
    zip: "11217",
    state: "NY",
    country: "US",
  },
  {
    time: new Date(Date.parse(new Date()) + 4 * 1000 * 60 * 60 * 24).toJSON(),
    title: "Forest Hills Stadium",
    category: "concert",
    description: "New York concert",
    price: 10,
    quantity: 1,
    upload: "1700626869150.png",
    address1: "1 Tennis Pl",
    address2: " ",
    city: "Forest Hills",
    zip: "10036",
    state: "NY",
    country: "US",
  },
];
/** Seeds the database with a user and some tasks */
const seed = async () => {
  const arr = [
    "reservation",
    "reservation",
    "reservation",
    "movies",
    "movies",
    "movies",
    "movies",
    "concert",
    "concert",
    "concert",
  ];
  await prisma.user.upsert({
    where: { username: "nguyenvo" },
    update: {},
    create: {
      username: "nguyenvo",
      password: "123456",
      email: "vophannguyen@gmail.com",
      firstName: "Nguyen",
      lastName: "Vo",
      items: {
        create: dbNewYork.map((item) => ({
          time: item.time,
          title: item.title,
          category: item.category,
          description: item.description,
          price: 10,
          quantity: 1,
          upload: "1700626869150.png",
          address1: item.address1,
          address2: " ",
          city: item.city,
          zip: item.zip,
          state: item.state,
          country: "US",
        })),
      },
    },
  });
  await prisma.user.upsert({
    where: { username: "anna" },
    update: {},
    create: {
      username: "anna",
      password: "123456",
      email: "anna@gmail.com",
      firstName: "Anna",
      lastName: "WaterHouse",
      items: {
        create: dbLosAngeles.map((item) => ({
          time: item.time,
          title: item.title,
          category: item.category,
          description: item.description,
          price: 10,
          quantity: 1,
          upload: "1700626869150.png",
          address1: item.address1,
          address2: " ",
          city: item.city,
          zip: item.zip,
          state: item.state,
          country: "US",
        })),
      },
    },
  });
  await prisma.user.upsert({
    where: { username: "yoona" },
    update: {},
    create: {
      username: "yoona",
      password: "123456",
      email: "yoona@gmail.com",
      firstName: "Yoona",
      lastName: "Choi",
      items: {
        create: dbChicagoBoston.map((item) => ({
          time: item.time,
          title: item.title,
          category: item.category,
          description: item.description,
          price: 10,
          quantity: 1,
          upload: "1700626869150.png",
          address1: item.address1,
          address2: " ",
          city: item.city,
          zip: item.zip,
          state: item.state,
          country: "US",
        })),
      },
    },
  });
};
seed()
  .then(async () => await prisma.$disconnect())
  .catch(async (err) => {
    console.error(err);
    await prisma.$disconnect();
    process.exit(1);
  });
