const prisma = require("../prisma");

const dbNewYork = [
  {
    time: new Date(Date.parse(new Date()) + 1 * 1000 * 60 * 60 * 24).toJSON(),
    title: "Carbone",
    category: "reservation",
    description: "New York restaurant",
    price: 10,
    quantity: 1,
    upload: "1700626869150.png",
    address1: "181 Thompson street",
    address2: " ",
    city: "New York",
    zip: "10012",
    state: "NY",
    country: "US",
  },
  {
    time: new Date(Date.parse(new Date()) + 4 * 1000 * 60 * 60 * 24).toJSON(),
    title: "COTE",
    category: "reservation",
    description: "New York restaurant",
    price: 10,
    quantity: 1,
    upload: "1700626869150.png",
    address1: "16 W22 Street",
    address2: " ",
    city: "New York",
    zip: "10012",
    state: "NY",
    country: "US",
  },
  {
    time: new Date(Date.parse(new Date()) + 6 * 1000 * 60 * 60 * 24).toJSON(),
    title: "Cafe Mogador",
    category: "reservation",
    description: "New York restaurant",
    price: 10,
    quantity: 1,
    upload: "1700626869150.png",
    address1: "133 Wythe Ave",
    address2: " ",
    city: "Brooklyn",
    zip: "11249",
    state: "NY",
    country: "US",
  },
  {
    time: new Date(Date.parse(new Date()) + 4 * 1000 * 60 * 60 * 24).toJSON(),
    title: "Cocoron",
    category: "reservation",
    description: "New York restaurant",
    price: 10,
    quantity: 1,
    upload: "1700626869150.png",
    address1: "16 Delancey St",
    address2: " ",
    city: "New York",
    zip: "10002",
    state: "NY",
    country: "US",
  },
  {
    time: new Date(Date.parse(new Date()) + 4 * 1000 * 60 * 60 * 24).toJSON(),
    title: "Bacaro",
    category: "reservation",
    description: "New York restaurant",
    price: 10,
    quantity: 1,
    upload: "1700626869150.png",
    address1: "136 Division Street",
    address2: " ",
    city: "New York",
    zip: "10002",
    state: "NY",
    country: "US",
  },
  {
    time: new Date(Date.parse(new Date()) + 4 * 1000 * 60 * 60 * 24).toJSON(),
    title: "AMC Empire",
    category: "movies",
    description: "New York movies",
    price: 10,
    quantity: 1,
    upload: "1700626869150.png",
    address1: "25 - 234 W42 st",
    address2: " ",
    city: "New York",
    zip: "10036",
    state: "NY",
    country: "US",
  },
  {
    time: new Date(Date.parse(new Date()) + 9 * 1000 * 60 * 60 * 24).toJSON(),
    title: "IPIC Theater",
    category: "movies",
    description: "New York movies",
    price: 10,
    quantity: 1,
    upload: "1700626869150.png",
    address1: "11 Fullton St",
    address2: " ",
    city: "New York",
    zip: "10038",
    state: "NY",
    country: "US",
  },
  {
    time: new Date(Date.parse(new Date()) + 3 * 1000 * 60 * 60 * 24).toJSON(),
    title: "BAM strong",
    category: "concert",
    description: "New York concert",
    price: 10,
    quantity: 1,
    upload: "1700626869150.png",
    address1: "651 Fulton",
    address2: " ",
    city: "New York",
    zip: "11217",
    state: "NY",
    country: "US",
  },
  {
    time: new Date(Date.parse(new Date()) + 4 * 1000 * 60 * 60 * 24).toJSON(),
    title: "Forest Hills Stadium",
    category: "concert",
    description: "New York concert",
    price: 10,
    quantity: 1,
    upload: "1700626869150.png",
    address1: "1 Tennis Pl",
    address2: " ",
    city: "Forest Hills",
    zip: "10036",
    state: "NY",
    country: "US",
  },
];
/** Seeds the database with a user and some tasks */
const seed = async () => {
  const arr = [
    "reservation",
    "reservation",
    "reservation",
    "movies",
    "movies",
    "movies",
    "movies",
    "concert",
    "concert",
    "concert",
  ];
  await prisma.user.upsert({
    where: { username: "nguyenvo" },
    update: {},
    create: {
      username: "nguyenvo",
      password: "123456",
      email: "vophannguyen@gmail.com",
      firstName: "Nguyen",
      lastName: "Vo",
      items: {
        create: dbNewYork.map((item) => ({
          time: item.time,
          title: item.title,
          category: item.category,
          description: item.description,
          price: 10,
          quantity: 1,
          upload: "1700626869150.png",
          address1: item.address1,
          address2: " ",
          city: item.city,
          zip: item.zip,
          state: item.state,
          country: "US",
        })),
      },
    },
  });
  await prisma.user.upsert({
    where: { username: "anna" },
    update: {},
    create: {
      username: "anna",
      password: "123456",
      email: "anna@gmail.com",
      firstName: "Anna",
      lastName: "WaterHouse",
      items: {
        create: arr.map((item) => ({
          time: new Date(
            Date.parse(new Date()) + 30 * 1000 * 60 * 60 * 24
          ).toJSON(),
          title: "Anna - " + item,
          category: item,
          description: "Anna Post Event: " + item,
          price: 11,
          quantity: 2,
          upload: "1700626869150.png",
          address1: "1074 albany park dr",
          address2: " ",
          city: "fort mill",
          zip: "29715",
          state: "SC",
          country: "US",
        })),
      },
    },
  });
  await prisma.user.upsert({
    where: { username: "yoona" },
    update: {},
    create: {
      username: "yoona",
      password: "123456",
      email: "yoona@gmail.com",
      firstName: "Yoona",
      lastName: "Choi",
      items: {
        create: arr.map((item) => ({
          time: new Date(
            Date.parse(new Date()) + 30 * 1000 * 60 * 60 * 24
          ).toJSON(),
          title: "Yoona - " + item,
          category: item,
          description: "Yoona Post Event: " + item,
          price: 9,
          quantity: 1,
          upload: "1700626869150.png",
          address1: "1074 albany park dr",
          address2: " ",
          city: "fort mill",
          zip: "29715",
          state: "SC",
          country: "US",
        })),
      },
    },
  });
};
seed()
  .then(async () => await prisma.$disconnect())
  .catch(async (err) => {
    console.error(err);
    await prisma.$disconnect();
    process.exit(1);
  });
